### ISSUE TITLE
Include blockchain.info?

### ISSUE THREAD

**Issue by jomo** [magoo/Blockchain-Graveyard#1]
https://www.reddit.com/r/Bitcoin/comments/37oxow/the_security_issue_of_blockchaininfos_android/crolfk4

tl;dr: Their Android app tried using `/dev/urandom`. If that wasn't available, they'd fall back to getting a seed from the website http://random.org (!) via HTTP (!!). At some point the website started redirecting to HTTPS and the app didn't check the status code (!!!), so the random seed was based on the (always equal) redirect message and generated a private key for [1Bn9ReEocMG1WEW1qYjuDrdFzEFFDCq43F](https://blockchain.info/address/1Bn9ReEocMG1WEW1qYjuDrdFzEFFDCq43F).

This resulted in "only" ~45 BTC of affected users being lost, but I think it's very interesting nonetheless.

**Comment by magoo** [comment]
Yikes. This may be pretty clowny and nasty, but it didn't result in a major catastrophe. Will save it for an honorable mention someday maybe since I'm trying to keep the list as brutal as possible.
